#!/usr/bin/env bash
#
# LightDM can't read files from the home directory (with good reason), so this
# script will simply copy the required files to /etc and /usr without symlinking
# them.

cd "$(dirname "$0")"

cp ../../user/wallpapers/Afbeeldingen/wallpapers/arc.png /usr/share/backgrounds/
cp ./index.theme /usr/share/icons/default/index.theme
[[ -d /etc/lightdm ]] && cp ./lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf
