#!/usr/bin/env bash
#
# This adds a patch that basically removes any checks from i3's `no_focus`
# directive. This is a dumb hack to work around plasma/i3 interactions and
# breaks further use of `no_focus`.

patch_dir="$(realpath $(dirname "$0"))"
cd $patch_dir

i3_location=~/.cache/pacaur/i3-gaps
if [[ ! -d $i3_location ]]; then
  echo "i3-gaps source directory ($i3_location) not found, skipping"
  exit 1
fi

cd $i3_location
[[ -f $i3_location/kde.patch ]] || echo -e "Installing KDE-patch for i3-gaps.\n\nNOTE: Pacaur will not apply the patch, use 'cd $i3_location && makepkg -fsic' to install manually."

git reset --hard origin/master > /dev/null
git am < $patch_dir/kde.patch > /dev/null
