#!/usr/bin/env bash

set -e

if [[ $2 == 'up' ]]; then
  nordvpn connect nl

  # Nordvpn's CLI messes up iptables. Without this you won't be able to host any
  # servers.
  iptables -C INPUT -d 127.0.0.1 -j ACCEPT 2>/dev/null || \
    iptables -I INPUT -d 127.0.0.1 -j ACCEPT

  # ip route add default dev tun0
  # ip route del 0.0.0.0/1
  # ip route del 128.0.0.0/1
fi
