#!/usr/bin/env bash

if [ "$2" != "up" ]; then
   exit
fi

# NordPy tends to cause the entire network connection to be unusable if the
# connection status suddenly changes, so we will ensure nothing's broken before
# we attempt to connect (which will change these settings back anyway)
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT

# This file might somehow get replaced with symlink to a nonexistent file
if [[ ! -e /etc/resolv.conf ]]; then
  rm -f /etc/resolv.conf
  cat >/etc/resolv.conf <<EOF
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF
fi

exec nordpy --quick-connect --wait-connection
