#!/bin/sh
[ -x ~/.xprofile ] && . ~/.xprofile

sxhkd &
compton &

[ -x $HOME/.dotfiles/bin/fix-java-nonparenting ] && \
  $HOME/.dotfiles/bin/fix-java-nonparenting &

feh --bg-fill $HOME/.dotfiles/configs/wallpapers/blur3.jpg &

/usr/lib/gnome-settings-daemon/gnome-settings-daemon-localeexec &
tint2 -c $HOME/.config/tint2/arc.tint2rc &
volumeicon &
dunst -config $HOME/.config/bspwm/dunstrc &
bspc config top_padding 47

# Keyboard repeat delay
xset r rate 250 15

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 15

bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config click_to_focus true

bspc config presel_feedback_color "#e7e8eb"

bspc rule -a vokoscreen state=floating
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
