#!/bin/sh
sxhkd &
/usr/lib/gnome-settings-daemon/gnome-settings-daemon-localeexec &
compton -b \
  --shadow \
  --fading \
  --inactive-dim 0.3 \
  --focus-exclude '_NET_WM_NAME@:s = "rofi"' &

feh --bg-fill $HOME/.dotfiles/configs/wallpapers/haskell.jpg &

export PANEL_FIFO=/tmp/panel-fifo
export PANEL_HEIGHT=24
export PANEL_FONT="-*-fixed-*-*-*-*-10-*-*-*-*-*-*-*"
export PANEL_WM_NAME=bspwm_panel

panel &

# Keyboard repeat delay
xset r rate 250 15

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config click_to_focus true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
