#!/bin/sh
[ -x ~/.xprofile ] && . ~/.xprofile

sxhkd &
compton --respect-prop-shadow &

# Wallpaper
feh --bg-fill \
  $HOME/.dotfiles/user/wallpapers/Afbeeldingen/wallpapers/blur3.jpg &

# Panel and applets
$HOME/.config/polybar/launch.sh &
volumeicon &
nm-applet &
dunst &
#bspc config top_padding 47

# Keyboard repeat delay
xset r rate 250 15

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 15

bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config click_to_focus true

bspc config presel_feedback_color "#e7e8eb"

# Some applications are better off floating by default
bspc rule -a Pavucontrol state=floating
bspc rule -a vokoscreen state=floating

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
