#!/usr/bin/env bash
#
# This script will install the arc-kde theme from
# https://github.com/PapirusDevelopmentTeam/arc-kde and replace the panel's SVG
# file to make it translucent.

cd "$(dirname "$0")"

repo_url='https://github.com/PapirusDevelopmentTeam/arc-kde'
theme_path=~/.local/share/plasma/desktoptheme/Arc-Dark-Transparent
tmp_dir=$(mktemp -d)

if [[ -d $theme_path ]]; then
  exit 0
fi

echo 'Installing transparency patches for arc-kde'

git clone --depth=1 $repo_url $tmp_dir 2> /dev/null
cp -r $tmp_dir/plasma/desktoptheme/Arc-Dark $theme_path

cp -r ./replacements/* $theme_path
sed -i 's/^Name=Arc Dark/Name=Arc Dark - Transparent/' $theme_path/metadata.desktop
